name: PrivateEncoderV2.0 Workflows 

on:
    push:
    workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://Dark-super-me:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           
       
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone -b alpha https://github.com/Col-Serra/light-Queue-Enc.git
       - name: editing files        
         continue-on-error: true
         run: |
            echo "from decouple import config

try:
    APP_ID = "5463494"
    API_HASH = "a0effeee51b8747084dab2e5f6fd7007"
    BOT_TOKEN = "1664051814:AAHBNAIKNHfLA_IBRZP2AeJ1jSMjQqcu8yg"
    DEV = 1322549723
    OWNER = "1137051365 1516771402 1604378785"
    FFMPEG = """ffmpeg -i '''{}''' -filter_complex "ass=Input.ass, drawtext=fontfile=Aclonica.ttf:text='\|\|  This Episode Was Downloaded From http\://t.me/Ani\_Mine \|\|  For More Similar Content Visit Our Telegram Channel @RS\_Community':bordercolor=black@0.35:borderw=3:fontcolor=white:fontsize=36:x=w-((2*w-200)*(t-1000)/90):y=lh+0.5:enable='between(t,1000,1200)'[out1]" -metadata:s:a:0 title="[Telegram: @RsTvAnime]" -metadata:s:a:1 title="[Telegram: @Ani_Mine]" -metadata:s:s:0 title="[Telegram: @Rs_community] - English" -metadata:s:s:1 title="[Telegram: @RsTvEncodes]" -map [out1] -map 0:a? -map 0:s? -map 0:t? -metadata title="Encoded by @RsTvEncodes For Telegram Channel @Ani_Mine" -c:v libx265 -pix_fmt yuv420p -preset slow -s 852x480 -crf 30 -b:v 420k -c:a libopus -ac 2 -vbr 2  -ab 32k -c:s copy -movflags +faststart '''{}''' -y"""
    THUMB = "https://telegra.ph//file/6370f098231e0bc94be70.jpg"
except Exception as e:
    print("Environment vars Missing")
    print("something went wrong")
    print(str(e))
    exit()" light-Queue-Enc/bot/config.py
       - name: Running light-Queue-Enc Bot 
         timeout-minutes: 300
         continue-on-error: true
         run: |
           cd light-Queue-Enc
           docker build -t compressor . && docker run compressor
           
       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
